paths:
  raw: data/raw
  interim: data/interim
  processed: data/processed
  reports: reports
  experiments: reports/experiments

features:
  predictors: ["granular1", "granular2", "granular3", "granular4", "granular5"]   
  target: ["aggregated1", "aggregated2"]                
  
split:
  shuffle: True 
  test_size: 0.2
  random_state: 3 # 2(agg1), 3(agg2)

nn:
  seed: 0
  input_dim: 5
  hidden_dims: [32,32]
  output_dim: 2
  epochs: 100
  batch_size: 8
  lr: 0.0005

